all:
	g++ ../interpolacion/interpolation.cpp ../integral/integral.cpp main.cpp -o main -std=c++14 -larmadillo
clean:
	rm -rf ../resultados
	mkdir ../resultados
	mkdir ../resultados/_Errores
	mkdir ../resultados/CS
	mkdir ../resultados/DD
	mkdir ../resultados/DF
	mkdir ../resultados/MS
	mkdir ../resultados/CI
	
install:
	mkdir ../resultados
	mkdir ../resultados/_Errores
	mkdir ../resultados/CS
	mkdir ../resultados/DD
	mkdir ../resultados/DF
	mkdir ../resultados/MS
	mkdir ../resultados/CI